# Generated by Django 3.1 on 2021-06-17 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IPT', '0002_auto_20210616_2054'),
    ]

    operations = [
        migrations.AddField(
            model_name='landunits',
            name='area_per_unit_ft',
            field=models.CharField(default='', max_length=80),
            preserve_default=False,
        ),
    ]
