# Generated by Django 3.1 on 2021-06-17 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IPT', '0003_landunits_area_per_unit_ft'),
    ]

    operations = [
        migrations.AddField(
            model_name='buildings',
            name='length',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='buildings',
            name='width',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
