# Generated by Django 3.1 on 2021-06-18 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IPT', '0004_auto_20210617_2103'),
    ]

    operations = [
        migrations.AddField(
            model_name='landdetails',
            name='area_ch',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
